name: Build MSI Installer (Advanced)

on:
  push:
    tags:
      - 'v*'

jobs:
  build-msi:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Setup Node.js 23
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'
        cache-dependency-path: scoreboard-app/package-lock.json
        
    - name: Restore .NET dependencies
      run: dotnet restore
      
    - name: Build frontend first
      run: |
        cd scoreboard-app
        npm install
        # Очищаем dist папку перед сборкой
        if (Test-Path "dist") { Remove-Item "dist" -Recurse -Force }
        npm run build
        cd ..
        
    - name: Build and publish scoreboard-backend
      run: |
        dotnet publish scoreboard-backend/scoreboard-backend.csproj -c Release -o ./publish --self-contained false
        
    - name: Create custom MSI project file
      run: |
        # Создаем временный MSI проект, который включает все файлы из publish
        $publishPath = "publish"
        $msiProjectContent = @"
        "DeployProject"
        {
        "VSVersion" = "3:800"
        "ProjectType" = "8:{978C614F-708E-4E1A-B201-565925725DBA}"
        "IsWebType" = "8:FALSE"
        "ProjectName" = "8:Install"
        "LanguageId" = "3:1033"
        "CodePage" = "3:1252"
        "UILanguageId" = "3:1033"
        "SccProjectName" = "8:"
        "SccLocalPath" = "8:"
        "SccAuxPath" = "8:"
        "SccProvider" = "8:"
            "Configurations"
            {
                "Release"
                {
                "DisplayName" = "8:Release"
                "IsDebugOnly" = "11:FALSE"
                "IsReleaseOnly" = "11:TRUE"
                "OutputFilename" = "8:Release\\Install.msi"
                "PackageFilesAs" = "3:1"
                "PackageFileSize" = "3:-2147483648"
                "CabType" = "3:1"
                "Compression" = "3:2"
                "SignOutput" = "11:FALSE"
                "CertificateFile" = "8:"
                "PrivateKeyFile" = "8:"
                "TimeStampServer" = "8:"
                "InstallerBootstrapper" = "3:2"
                    "BootstrapperCfg:{63ACBE69-63AA-4F98-B2B6-99F9E24495F2}"
                    {
                    "Enabled" = "11:TRUE"
                    "PromptEnabled" = "11:TRUE"
                    "PrerequisitesLocation" = "2:1"
                    "Url" = "8:"
                    "ComponentsUrl" = "8:"
                        "Items"
                        {
                            "{EDC2488A-8267-493A-A98E-7D9C3B36CDF3}:Microsoft.NetCore.CoreRuntime.9.0.x64"
                            {
                            "Name" = "8:.NET Runtime 9.0.7 (x64)"
                            "ProductCode" = "8:Microsoft.NetCore.CoreRuntime.9.0.x64"
                            }
                        }
                    }
                }
            }
            "Deployable"
            {
                "DefaultFeature"
                {
                "Name" = "8:DefaultFeature"
                "Title" = "8:"
                "Description" = "8:"
                }
                "ExternalPersistence"
                {
                    "LaunchCondition"
                    {
                        "{A06ECF26-33A3-4562-8140-9B0E340D4F24}:_E8117EA1DB5D47D9B1EAF0DDFD36DCC0"
                        {
                        "Name" = "8:.NET Core"
                        "Message" = "8:[VSDNETCOREMSG]"
                        "AllowLaterVersions" = "11:FALSE"
                        "InstallUrl" = "8:https://dotnet.microsoft.com/download/dotnet-core/[NetCoreVerMajorDotMinor]"
                        "IsNETCore" = "11:TRUE"
                        "Architecture" = "2:0"
                        "Runtime" = "2:0"
                        }
                    }
                }
                "File"
                {
                }
                "FileType"
                {
                }
                "Folder"
                {
                    "{3C67513D-01DD-4637-8A68-80971EB9504F}:_7EEEDA42762A41B199C0322F15CB7135"
                    {
                    "DefaultLocation" = "8:[ProgramFilesFolder][Manufacturer]\\[ProductName]"
                    "Name" = "8:#1925"
                    "AlwaysCreate" = "11:FALSE"
                    "Condition" = "8:"
                    "Transitive" = "11:FALSE"
                    "Property" = "8:TARGETDIR"
                        "Folders"
                        {
                        }
                    }
                }
                "LaunchCondition"
                {
                }
                "Locator"
                {
                }
                "MsiBootstrapper"
                {
                "LangId" = "3:1033"
                "RequiresElevation" = "11:FALSE"
                }
                "Product"
                {
                "Name" = "8:Microsoft Visual Studio"
                "ProductName" = "8:Scoreboard Application"
                "ProductCode" = "8:{EA60C9E5-F6B3-49D4-A3F0-3EBEB08BFA2B}"
                "PackageCode" = "8:{D56EDD54-09C6-4CC3-97CE-47B965F80EEA}"
                "UpgradeCode" = "8:{C22826E9-82D7-48BD-B22F-348140261D4C}"
                "AspNetVersion" = "8:4.0.30319.0"
                "RestartWWWService" = "11:FALSE"
                "RemovePreviousVersions" = "11:FALSE"
                "DetectNewerInstalledVersion" = "11:TRUE"
                "InstallAllUsers" = "11:FALSE"
                "ProductVersion" = "8:${{ github.ref_name }}"
                "Manufacturer" = "8:Default Company Name"
                "ARPHELPTELEPHONE" = "8:"
                "ARPHELPLINK" = "8:"
                "Title" = "8:Scoreboard Installer"
                "Subject" = "8:"
                "ARPCONTACT" = "8:Default Company Name"
                "Keywords" = "8:"
                "ARPCOMMENTS" = "8:"
                "ARPURLINFOABOUT" = "8:"
                "ARPPRODUCTICON" = "8:"
                "ARPIconIndex" = "3:0"
                "SearchPath" = "8:"
                "UseSystemSearchPath" = "11:TRUE"
                "TargetPlatform" = "3:0"
                "PreBuildEvent" = "8:"
                "PostBuildEvent" = "8:"
                "RunPostBuildEvent" = "3:0"
                }
                "Registry"
                {
                }
                "Sequences"
                {
                }
                "Shortcut"
                {
                }
                "UserInterface"
                {
                    "{DF760B10-853B-4699-99F2-AFF7185B4A62}:_0469CFF931BD45EDB572443652B4BE81"
                    {
                    "Name" = "8:#1901"
                    "Sequence" = "3:1"
                    "Attributes" = "3:2"
                        "Dialogs"
                        {
                            "{688940B3-5CA9-4162-8DEE-2993FA9D8CBC}:_F1F0313AE95848BD972918C15FB6C278"
                            {
                            "Sequence" = "3:100"
                            "DisplayName" = "8:Progress"
                            "UseDynamicProperties" = "11:TRUE"
                            "IsDependency" = "11:FALSE"
                            "SourcePath" = "8:<VsdDialogDir>\\VsdProgressDlg.wid"
                                "Properties"
                                {
                                    "BannerBitmap"
                                    {
                                    "Name" = "8:BannerBitmap"
                                    "DisplayName" = "8:#1001"
                                    "Description" = "8:#1101"
                                    "Type" = "3:8"
                                    "ContextData" = "8:Bitmap"
                                    "Attributes" = "3:4"
                                    "Setting" = "3:1"
                                    "UsePlugInResources" = "11:TRUE"
                                    }
                                    "ShowProgress"
                                    {
                                    "Name" = "8:ShowProgress"
                                    "DisplayName" = "8:#1009"
                                    "Description" = "8:#1109"
                                    "Type" = "3:5"
                                    "ContextData" = "8:1;True=1;False=0"
                                    "Attributes" = "3:0"
                                    "Setting" = "3:0"
                                    "Value" = "3:1"
                                    "DefaultValue" = "3:1"
                                    "UsePlugInResources" = "11:TRUE"
                                    }
                                }
                            }
                        }
                    }
                }
                "MergeModule"
                {
                }
                "File"
                {
        "@
        
        # Добавляем все файлы из publish директории
        $files = Get-ChildItem -Path $publishPath -Recurse -File
        foreach ($file in $files) {
            $relativePath = $file.FullName.Substring((Get-Location).Path.Length + 1)
            $targetPath = $relativePath.Replace($publishPath, "")
            $targetPath = $targetPath.TrimStart("\")
            
            $msiProjectContent += @"
                    "{5259A561-127C-4D43-A0A1-72F10C7B3BF8}:$((New-Guid).ToString().Replace('-', '').Substring(0, 16))"
                    {
                    "SourcePath" = "8:$relativePath"
                    "TargetName" = "8:$($file.Name)"
                    "Tag" = "8:"
                    "Folder" = "8:_7EEEDA42762A41B199C0322F15CB7135"
                    "Condition" = "8:"
                    "Transitive" = "11:FALSE"
                    "Vital" = "11:TRUE"
                    "ReadOnly" = "11:FALSE"
                    "Hidden" = "11:FALSE"
                    "System" = "11:FALSE"
                    "Permanent" = "11:FALSE"
                    "SharedLegacy" = "11:FALSE"
                    "PackageAs" = "3:1"
                    "Register" = "3:1"
                    "Exclude" = "11:FALSE"
                    "IsDependency" = "11:FALSE"
                    "IsolateTo" = "8:"
                    "ProjectOutputGroupRegister" = "3:1"
                    "OutputConfiguration" = "8:"
                    "OutputGroupCanonicalName" = "8:BuiltProjectOutputGroup"
                    "OutputProjectGuid" = "8:{F33B116B-25B1-429E-BD5F-79F397918269}"
                    "ShowKeyOutput" = "11:TRUE"
                        "ExcludeFilters"
                        {
                        }
                    }
        "@
        }
        
        $msiProjectContent += @"
                }
            }
        }
        "@
        
        $msiProjectContent | Out-File -FilePath "Install/Install-Advanced.vdproj" -Encoding UTF8
        
    - name: Build advanced MSI installer
      run: |
        # Используем MSBuild для сборки MSI инсталлера
        msbuild Install/Install-Advanced.vdproj /p:Configuration=Release /p:Platform="Any CPU" /p:DeployOnBuild=true
        
    - name: Upload MSI artifact
      uses: actions/upload-artifact@v4
      with:
        name: scoreboard-installer-advanced-${{ github.ref_name }}
        path: Install/Release/Install.msi
        retention-days: 30
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Install/Release/Install.msi
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 