name: Build Portable Application

on:
  push:
    tags:
      - 'v*'

jobs:
  build-portable:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Setup Node.js 23
      uses: actions/setup-node@v4
      with:
        node-version: '23'
        cache: 'npm'
        cache-dependency-path: scoreboard-app/package-lock.json
        
    - name: Restore .NET dependencies
      run: dotnet restore
      
    - name: Build and publish scoreboard-backend
      run: |
        dotnet publish scoreboard-backend/scoreboard-backend.csproj -c Release -o ./portable --self-contained false
        
    - name: Create portable package
      shell: pwsh
      run: |
        # Запускаем скрипт создания portable версии
        .\scripts\create-portable.ps1 -Version "${{ github.ref_name }}" -PublishPath "portable"
        
    - name: Create portable ZIP
      run: |
        # Создаем ZIP архив
        Compress-Archive -Path "portable-release\*" -DestinationPath "Scoreboard-Portable-${{ github.ref_name }}.zip" -Force
        
    - name: Upload portable artifact
      uses: actions/upload-artifact@v4
      with:
        name: scoreboard-portable-${{ github.ref_name }}
        path: Scoreboard-Portable-${{ github.ref_name }}.zip
        retention-days: 30
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Scoreboard-Portable-${{ github.ref_name }}.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 